# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Conta < Formula
  desc "A Cloud native webhook service"
  homepage "https://getconvoy.io/"
  version "0.6.5"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Dotunj/convoy/releases/download/v0.6.5/conta_0.6.5_darwin_arm64.tar.gz"
      sha256 "7904199c9c4d650106f716fa8f0edfacc03aa53873016b1563a89ea64b35da7a"

      def install
        bin.install "conta"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Dotunj/convoy/releases/download/v0.6.5/conta_0.6.5_darwin_amd64.tar.gz"
      sha256 "c599e136879b8af64e235b344b3265a698864da3522bc1d09f0673e6a16c4c7e"

      def install
        bin.install "conta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dotunj/convoy/releases/download/v0.6.5/conta_0.6.5_linux_arm64.tar.gz"
      sha256 "2d1b9e62ddd8e43dcddbdfbcb87bdbd5e3a8a1bb8a22b29c95eef22b1aa991a5"

      def install
        bin.install "conta"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Dotunj/convoy/releases/download/v0.6.5/conta_0.6.5_linux_amd64.tar.gz"
      sha256 "704a79134afc6ea501def51d28a992c8856c3fa4ebc349a2123f38cd4406512c"

      def install
        bin.install "conta"
      end
    end
  end
end
