# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pita < Formula
  desc "Binary Distribution for Pita"
  homepage "https://github.com/dotunj/homebrew-pita"
  version "0.1.10"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Dotunj/pita/releases/download/v0.1.10/pita_0.1.10_darwin_arm64.tar.gz"
      sha256 "14c45eff04912fac0d255c23a27590bfbeccefc279ee5c7bac948340373c1eb8"

      def install
        bin.install "pita"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Dotunj/pita/releases/download/v0.1.10/pita_0.1.10_darwin_x86_64.tar.gz"
      sha256 "59a3dd4e306b299eb3e2d6e8f6bd719b51f1c396710dd2db6c73d9646c68bedc"

      def install
        bin.install "pita"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dotunj/pita/releases/download/v0.1.10/pita_0.1.10_linux_arm64.tar.gz"
      sha256 "c256c232cb8d27484cdd146ce84dc8b9b34b81d9bbc14367340410aec1dbf322"

      def install
        bin.install "pita"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Dotunj/pita/releases/download/v0.1.10/pita_0.1.10_linux_x86_64.tar.gz"
      sha256 "de1b1d3a8903cb4770c473d7c4b6ec3332ed38fbc7064cadec1b12998d96341d"

      def install
        bin.install "pita"
      end
    end
  end
end
