# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pita < Formula
  desc "Binary Distribution for Pita"
  homepage "https://github.com/dotunj/homebrew-pita"
  version "0.1.11"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Dotunj/pita/releases/download/v0.1.11/pita_0.1.11_darwin_arm64.tar.gz"
      sha256 "f33890e180625c1d9dcbcf891a4372345e52a552e4dbd0a35f89972f6369edcb"

      def install
        bin.install "pita"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Dotunj/pita/releases/download/v0.1.11/pita_0.1.11_darwin_x86_64.tar.gz"
      sha256 "40c1f34cfb688c7a8ecf9ab2d1d9a12021f8c5196b8a0d70b8bdc64099e3afea"

      def install
        bin.install "pita"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dotunj/pita/releases/download/v0.1.11/pita_0.1.11_linux_arm64.tar.gz"
      sha256 "69c85ebe688f9ce7803e6dc565220ab8a17afbaa2b09cd55319c2552f63622aa"

      def install
        bin.install "pita"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Dotunj/pita/releases/download/v0.1.11/pita_0.1.11_linux_x86_64.tar.gz"
      sha256 "ca1fd683449fc0102bebe5b343762631fcaa47f3f8c0b1ece6310751ed86a8b7"

      def install
        bin.install "pita"
      end
    end
  end
end
