# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pvent < Formula
  desc "Send Events to different Message brokers"
  homepage "https://github.com/dotunj/pvent"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dotunj/pvent/releases/download/v0.0.1/pvent_0.0.1_darwin_amd64.tar.gz"
      sha256 "5db302327bf069cb1743ff207bda24e25d0e5bd44c0bdefd2509d9e4f90e9cb0"

      def install
        bin.install "pvent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dotunj/pvent/releases/download/v0.0.1/pvent_0.0.1_darwin_arm64.tar.gz"
      sha256 "6fbeccdce10d2f621b776c3da90f3837827d3377ccf98294973dc446a8b06222"

      def install
        bin.install "pvent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dotunj/pvent/releases/download/v0.0.1/pvent_0.0.1_linux_arm64.tar.gz"
      sha256 "187bc4046877e090232a1328047bd26e94842281460286cbfee3af5bf247b734"

      def install
        bin.install "pvent"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Dotunj/pvent/releases/download/v0.0.1/pvent_0.0.1_linux_amd64.tar.gz"
      sha256 "207ebad441619fa8d46a4217b4690286e81aace9572a8fcd179a214155ecefb3"

      def install
        bin.install "pvent"
      end
    end
  end
end
