# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HomebrewPita < Formula
  desc "Binary Distribution for Pita"
  homepage "https://github.com/dotunj/homebrew-pita"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dotunj/pita/releases/download/v0.0.5/homebrew-pita_0.0.5_darwin_x86_64.tar.gz"
      sha256 "4d4cccdee295638086b9b450d3b433288bc461e7966357d3f41ac799c1698eb2"

      def install
        bin.install "homebrew-pita"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Dotunj/pita/releases/download/v0.0.5/homebrew-pita_0.0.5_linux_x86_64.tar.gz"
      sha256 "c5d412017d9a06f8f8b3d55f2e6dd1f6cb01695e9c776e87c6925c918b6dc393"

      def install
        bin.install "homebrew-pita"
      end
    end
  end
end
